// Generated by https://quicktype.io

export interface CoursesResponse {
  data: CoursesResponseData
  meta: Meta
}

export interface CoursesResponseData {
  id: number
  attributes: PurpleAttributes
}

export interface PurpleAttributes {
  titulo: string
  contenido: string
  createdAt: string
  updatedAt: string
  publishedAt: string
  imagen: Imagen
}

export interface Imagen {
  data: ImagenData
}

export interface ImagenData {
  id: number
  attributes: FluffyAttributes
}

export interface FluffyAttributes {
  name: string
  alternativeText: string
  caption: string
  width: number
  height: number
  formats: Formats
  hash: string
  ext: string
  mime: string
  size: number
  url: string
  previewUrl: null
  provider: string
  provider_metadata: ProviderMetadata
  createdAt: string
  updatedAt: string
}

export interface Formats {
  thumbnail: Large
  large: Large
  medium: Large
  small: Large
}

export interface Large {
  name: string
  hash: string
  ext: string
  mime: string
  path: null
  width: number
  height: number
  size: number
  url: string
  provider_metadata: ProviderMetadata
}

export interface ProviderMetadata {
  public_id: string
  resource_type: string
}

export interface Meta {}
